src/main/java/edu/tamu/app/model/CatalogHolding.java, src/main/java/edu/tamu/app/model/PersistedButton.java, src/main/java/edu/tamu/app/service/GetItForMeService.java, src/main/java/edu/tamu/app/service/VoyagerCatalogService.java, src/main/resources/buttons.properties
- Add/update publication date and edition to CatalogHolding and button parameters
- Add enumeration and chron to edition parameter for multi-volumes
=> [B03838] Add fields to Illiad/Aeon links - MERGE

src/main/java/edu/tamu/app/controller/CatalogAccessController.java, src/main/java/edu/tamu/app/model/AbstractButtonPresentation.java, src/main/java/edu/tamu/app/model/ButtonFormPresentation.java, src/main/java/edu/tamu/app/model/ButtonLinkPresentation.java, src/main/java/edu/tamu/app/model/ButtonPresentation.java, src/main/java/edu/tamu/app/service/GetItForMeService.java, src/main/resources/application.properties, src/main/resources/buttons.properties
This PR allows for multiple types of button presentations.
For now, there are the standard link implementation, and a form based implementation for the 'default' button, which is triggered by very large item counts.
This is accomplished with the ButtonPresentation abstraction.
=> [B03958] Rework of the default/large volume button behavior

src/main/java/edu/tamu/app/service/GetItForMeService.java, src/main/resources/application.properties
To support the new Hathi Trust javascript button, this PR allows for blocking all buttons at the item level based on two new configuration values for patronGroup and location.
=> Configurable GIFM button override

src/main/java/edu/tamu/app/controller/CatalogAccessController.java
=> [79] New endpoints and modifications to support standalone GIFM Service

src/main/java/edu/tamu/app/config/RestConfig.java, src/main/java/edu/tamu/app/service/AbstractCatalogService.java, src/main/java/edu/tamu/app/service/CatalogService.java, src/main/java/edu/tamu/app/service/CatalogServiceFactory.java, src/main/java/edu/tamu/app/service/FolioCatalogService.java, src/main/java/edu/tamu/app/service/VoyagerCatalogService.java, src/main/java/edu/tamu/app/utility/Marc21Xml.java, src/main/resources/config/catalogs.json, src/test/java/edu/tamu/app/controller/MockCatalogService.java
This will involve determining server, port, and authentication properties for connecting to a particular FOLIO instance.
This implements the two methods that will actually retrieve raw records/holdings from FOLIO.
This will parse, package, and return the records as instances of the generalized CatalogHolding class.
resolves #72
=> Issue 72: Create a FOLIO implementation of the Catalog Service interface

.github/workflows/build.yml, README.md, pom.xml
Support for Coveralls (and related) is added, allowing for there to be a working coverage Badge.
=> Issue 83: Add Github Actions for CatalogService.

service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java
Further generalize the tests.
The same UIN is used everywhere, make it a static constant string.
There already are folio and voyager catalog strings, use them.
The "loan" and "fines" strings used in the context of endpoints are used all over the place, also make them static constant strings.
Document the Path and Query parameters.
The code was adding the specialized "loan" and "fines" endpoint strings to the get() call of mockMvc.perform().
It should not be used as such as those are specially reserved exclusively for Path Parameters.
Instead, concatenate the string.
Massively reduce the repeated code, further abstracting most of the file.
Clean up the structure a bit.
It can be very confusing having helper functions randomly in between test functions.
Move all of the helper functions to …
=> Improve patron controller tests and fix problems.

service/src/main/java/edu/tamu/catalog/controller/PatronController.java, service/src/main/java/edu/tamu/catalog/service/CatalogService.java, service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java, service/src/main/java/edu/tamu/catalog/service/VoyagerCatalogService.java, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java, service/src/test/resources/mock/patron/accountRenewableLoanItem.json
=> [93] Loan Item Renewals

service/src/main/java/edu/tamu/catalog/controller/PatronController.java, service/src/main/java/edu/tamu/catalog/model/FolioHoldCancellation.java, service/src/main/java/edu/tamu/catalog/properties/FolioProperties.java, service/src/main/java/edu/tamu/catalog/service/CatalogService.java, service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java, service/src/main/java/edu/tamu/catalog/service/VoyagerCatalogService.java, service/src/main/resources/catalogs/folio.json, service/src/test/java/edu/tamu/catalog/config/CatalogServiceConfigTest.java, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java, service/src/test/java/edu/tamu/catalog/service/FolioCatalogServiceTest.java, service/src/test/resources/catalogs/folio.json, service/src/test/resources/mock/patron/accountCancelHoldRequest.json, service/src/test/resources/mock/patron/accountCancelHoldResponse.json
=> [MERGER] Issue 96: FOLIO implementation of request cancellation.

service/src/main/java/edu/tamu/catalog/controller/PatronController.java, service/src/main/java/edu/tamu/catalog/model/FolioHoldCancellation.java, service/src/main/java/edu/tamu/catalog/properties/FolioProperties.java, service/src/main/java/edu/tamu/catalog/service/CatalogService.java, service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java, service/src/main/java/edu/tamu/catalog/service/VoyagerCatalogService.java, service/src/main/resources/catalogs/folio.json, service/src/test/java/edu/tamu/catalog/config/CatalogServiceConfigTest.java, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java, service/src/test/java/edu/tamu/catalog/service/FolioCatalogServiceTest.java, service/src/test/resources/catalogs/folio.json, service/src/test/resources/mock/patron/accountCancelHoldRequest.json, service/src/test/resources/mock/patron/accountCancelHoldResponse.json
=> Issue 96: FOLIO implementation of request cancellation.

service/src/main/java/edu/tamu/catalog/controller/PatronController.java, service/src/main/java/edu/tamu/catalog/service/CatalogService.java, service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java, service/src/main/java/edu/tamu/catalog/service/VoyagerCatalogService.java, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java
=> [89][MERGER] Blocks endpoint and pseudo FOLIO implementation

domain/src/main/java/edu/tamu/catalog/domain/model/FeeFine.java, domain/src/main/java/edu/tamu/catalog/domain/model/HoldRequest.java, domain/src/main/java/edu/tamu/catalog/domain/model/HoldingsRecord.java, domain/src/test/java/edu/tamu/catalog/domain/model/FeeFineTest.java, domain/src/test/java/edu/tamu/catalog/domain/model/HoldRequestTest.java, domain/src/test/java/edu/tamu/catalog/domain/model/HoldingsRecordTest.java, service/src/main/java/edu/tamu/catalog/model/FolioHoldCancellation.java, service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java, service/src/test/resources/mock/response/catalog/fines.json, service/src/test/resources/mock/response/catalog/requests.json
=> [MERGER] Issue 125: Loans, FeeFines (Charges), and Holds should all include itemId as well as instanceId.

README.md, service/pom.xml, service/src/docs/asciidocs/patronAPI.adoc, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTestBase.java, service/src/test/resources/mock/response/catalog/fines.json, service/src/test/resources/mock/response/patron/account.json, service/src/test/resources/mock/response/patron/accountDateParseError.json
resolves #120
relates TAMULib/APISpecs/pull/6
=> Cleanup Tests and Improve API Documentation Presentation

service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java, service/src/test/java/edu/tamu/catalog/controller/PatronControllerTest.java
=> Issue 89: simplify and check manual blocks as well

service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java
=> FOLIO: location names should be based on discoveryDisplayName field

service/pom.xml
=> [169] Weaver dependency version in the parent pom is different than the version in the service pom for catalog service.

service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java, service/src/test/resources/mock/response/catalog/loans.json
=> [167] Added discoveryDisplayName in Loan Response

service/src/main/resources/catalogs/evans.json, service/src/main/resources/catalogs/folio.json, service/src/main/resources/catalogs/msl.json
=> Hard coded prod urls removed from catalog config

service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java
=> folio: auto translate instance hrid to uuid for getHoldingsByBibId

docker-compose.yml, example.env
The DEPLOYING.md file specifies docker-compose. This PR is to get that to work with minimal change and effort.
Container orchestration.
- [-] Bug fix (non-breaking change which fixes an issue)
- [-] New feature (non-breaking change which adds functionality)
- [-] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [-] This change requires a documentation update
Copy example.env and run `docker-compose up`.
=> Add minimal docker compose

service/src/main/java/edu/tamu/catalog/service/FolioCatalogService.java
Doug found empty object inside empty array... `holdingsStatement` missing statement and any other property
```
[{}]
```
Null/Empty check
mvn clean spring-boot:run
=> Empty object inside empty array
